# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [48]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [49]:
file_loc = "../WeatherPy/output_data/cities.csv"
weather_df = pd.read_csv(file_loc)
weather_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Mahajanga,-15.7167,46.3167,84.20,84,20,3.44,MG,1617600771
1,1,Puerto Ayora,-0.7393,-90.3518,75.99,95,44,1.12,EC,1617600771
2,2,Jamestown,42.0970,-79.2353,37.40,65,1,4.61,US,1617600772
3,3,Hermanus,-34.4187,19.2345,63.00,92,99,1.01,ZA,1617600772
4,4,Sitka,57.0531,-135.3300,39.20,93,90,9.22,US,1617600773
...,...,...,...,...,...,...,...,...,...,...
570,570,Anjiang,27.3194,110.1031,51.98,91,100,2.42,CN,1617600993
571,571,Necochea,-38.5473,-58.7368,57.99,94,0,1.99,AR,1617600993
572,572,Seymour,38.9592,-85.8903,55.00,66,68,5.64,US,1617600993
573,573,Teguise,29.0605,-13.5640,62.60,77,40,4.61,ES,1617600994
574,574,Evensk,61.9500,159.2333,17.38,62,100,17.05,RU,1617600994

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [50]:
gmaps.configure(api_key=g_key)

In [51]:
locations = weather_df[["Lat", "Lng"]].astype(float)
humidity = weather_df["Humidity"].astype(float)

In [52]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                dissipating=False, max_intensity=100,
                                point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [72]:
weather2 = weather_df.loc[weather_df["Max Temp"] < 90]
weather3 = weather2.loc[weather2["Max Temp"] > 70]
weather4 = weather3.loc[weather3["Wind Speed"] < 20]
weather5 = weather4.loc[weather4["Cloudiness"] < 20]
hotel_df = weather5.reset_index()
hotel_df = hotel_df.drop(["index", "Unnamed: 0"], axis=1)
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Pitimbu,-7.4706,-34.8086,77.00,88,0,4.61,BR,1617600773
1,Busselton,-33.6500,115.3333,84.00,51,2,3.00,AU,1617600779
2,Grand Gaube,-20.0064,57.6608,84.99,70,5,7.00,MU,1617600808
3,Xai-Xai,-25.0519,33.6442,74.50,67,0,2.26,MZ,1617600811
4,Alice Springs,-23.7000,133.8833,89.01,28,0,9.22,AU,1617600815
5,São Filipe,14.8961,-24.4956,73.27,71,0,7.00,CV,1617600816
6,Fare,-16.7000,-151.0167,82.42,74,5,15.82,PF,1617600822
7,Geraldton,-28.7667,114.6000,80.60,57,12,14.97,AU,1617600833
8,Salalah,17.0151,54.0924,82.40,69,0,3.44,OM,1617600843
9,Sonāmura,23.4719,91.2664,86.00,42,1,8.05,IN,1617600847
10,Verāval,20.9000,70.3667,86.70,52,0,9.69,IN,1617600849
11,Faanui,-16.4833,-151.7500,82.81,74,14,16.15,PF,1617600850
12,Manicoré,-5.8092,-61.3003,75.20,100,0,1.81,BR,1617600851
13,Cidreira,-30.1811,-50.2056,71.55,79,2,16.51,BR,1617600853
14,Neuquén,-38.9516,-68.0591,71.60,64,0,2.30,AR,1617600856
15,Hambantota,6.1241,81.1185,87.80,70,0,6.91,LK,1617600865
16,São José da Tapera,-9.5583,-37.3811,71.37,96,10,3.51,BR,1617600866
17,Siavonga,-16.5382,28.7088,72.45,65,0,5.03,ZM,1617600867
18,Filingué,14.3521,3.3168,75.49,9,0,9.62,NE,1617600872
19,Shiggaon,15.0000,75.2333,86.00,39,0,9.22,IN,1617600881
20,Albury,-36.0833,146.9167,86.00,45,0,9.22,AU,1617600629
21,Yulara,-25.2406,130.9889,86.00,19,2,12.66,AU,1617600896
22,Makakilo City,21.3469,-158.0858,73.40,68,1,8.05,US,1617600908
23,Port Blair,11.6667,92.7500,85.24,65,15,10.78,IN,1617600922
24,Le Port,-20.9373,55.2919,86.00,58,0,11.50,RE,1617600922
25,Maragogi,-9.0122,-35.2225,77.27,79,11,8.46,BR,1617600927
26,Lere,10.3870,8.5726,72.36,17,6,4.36,NG,1617600846
27,Conde,-7.2597,-34.9075,77.00,88,0,4.61,BR,1617600934
28,Goundam,16.4145,-3.6708,77.50,7,9,6.49,ML,1617600934
29,Wagga Wagga,-35.1167,147.3667,84.99,37,0,3.44,AU,1617600938
30,Agadez,19.7500,10.2500,70.38,11,0,6.60,NE,1617600947
31,Biltine,14.5333,20.9167,80.53,10,18,15.86,TD,1617600963
32,Pita,10.8333,-12.5833,72.21,76,19,0.76,GN,1617600963
33,Prado,-17.3411,-39.2208,72.57,89,15,5.37,BR,1617600968
34,Manacapuru,-3.2997,-60.6206,77.00,94,0,1.14,BR,1617600968
35,Bilma,18.6853,12.9164,72.84,10,0,6.53,NE,1617600976
36,Wattegama,6.7989,81.4808,87.80,70,0,6.91,LK,1617600977
37,Gweta,-20.1833,25.2333,71.94,57,0,8.63,BW,1617600978
38,Madarounfa,13.3087,7.1560,74.07,10,7,8.86,NE,1617600992

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [93]:
hotel_df["Hotel Name"] = ""

In [94]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "rankby": "distance",
    "type": "lodging",
    "key": g_key,
}

for index, row in hotel_df.iterrows():
    
    coordinates = f"{row['Lat']}, {row['Lng']}"
    params["location"] = coordinates
    print(f"Retrieving Results for Index {index}: {coordinates}.")
    response = requests.get(base_url, params=params).json()
    
    results = response["results"]
    
    try:
        print(f"Closest hotel to {coordinates}: {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Retrieving Results for Index 0: -7.4706, -34.8086.
Closest hotel to -7.4706, -34.8086: Solar da Família Andrade - Pitimbu.
Retrieving Results for Index 1: -33.65, 115.3333.
Closest hotel to -33.65, 115.3333: Pearls Place.
Retrieving Results for Index 2: -20.0064, 57.6608.
Closest hotel to -20.0064, 57.6608: Talipot Lodge.
Retrieving Results for Index 3: -25.0519, 33.6442.
Closest hotel to -25.0519, 33.6442: Complexo da Familia.
Retrieving Results for Index 4: -23.7, 133.8833.
Closest hotel to -23.7, 133.8833: Aurora Alice Springs.
Retrieving Results for Index 5: 14.8961, -24.4956.
Closest hotel to 14.8961, -24.4956: Pensao ELIANE E CLARICE.
Retrieving Results for Index 6: -16.7, -151.0167.
Closest hotel to -16.7, -151.0167: HIRO.
Retrieving Results for Index 7: -28.7667, 114.6.
Closest hotel to -28.7667, 114.6: Ocean Centre Hotel.
Retrieving Results for Index 8: 17.0151, 54.0924.
Closest hotel to 17.0151, 54.0924: Muscat International Hotel plaza Salalah.
Retrieving Results for Index 9: 23.4719, 91.2664.
Closest hotel to 23.4719, 91.2664: Sorojini Guest House.
Retrieving Results for Index 10: 20.9, 70.3667.
Closest hotel to 20.9, 70.3667: Jayesh fofandi.
Retrieving Results for Index 11: -16.4833, -151.75.
Closest hotel to -16.4833, -151.75: Teina Pascale.
Retrieving Results for Index 12: -5.8092, -61.3003.
Closest hotel to -5.8092, -61.3003: Hotel Durval.
Retrieving Results for Index 13: -30.1811, -50.2056.
Closest hotel to -30.1811, -50.2056: Novo Litoral Norte Hotel.
Retrieving Results for Index 14: -38.9516, -68.0591.
Closest hotel to -38.9516, -68.0591: Rodrigo Manuel Notarío.
Retrieving Results for Index 15: 6.1241, 81.1185.
Closest hotel to 6.1241, 81.1185: Capri Moon Hotel.
Retrieving Results for Index 16: -9.5583, -37.3811.
Closest hotel to -9.5583, -37.3811: Pousada Felicia.
Retrieving Results for Index 17: -16.5382, 28.7088.
Closest hotel to -16.5382, 28.7088: Lavongora Waterfront Lodge.
Retrieving Results for Index 18: 14.3521, 3.3168.
Missing field/result... skipping.
Retrieving Results for Index 19: 15.0, 75.2333.
Closest hotel to 15.0, 75.2333: prasath baddi hottel.
Retrieving Results for Index 20: -36.0833, 146.9167.
Closest hotel to -36.0833, 146.9167: Mantra Albury Hotel.
Retrieving Results for Index 21: -25.2406, 130.9889.
Closest hotel to -25.2406, 130.9889: Ayers Rock Campground.
Retrieving Results for Index 22: 21.3469, -158.0858.
Closest hotel to 21.3469, -158.0858: エレン.
Retrieving Results for Index 23: 11.6667, 92.75.
Closest hotel to 11.6667, 92.75: Sea Shell Port Blair.
Retrieving Results for Index 24: -20.9373, 55.2919.
Closest hotel to -20.9373, 55.2919: Gromicile.
Retrieving Results for Index 25: -9.0122, -35.2225.
Closest hotel to -9.0122, -35.2225: Maragogi Pousada e Hostel Central | Mergulhodeponta.
Retrieving Results for Index 26: 10.387, 8.5726.
Missing field/result... skipping.
Retrieving Results for Index 27: -7.2597, -34.9075.
Closest hotel to -7.2597, -34.9075: Sulga lombra.
Retrieving Results for Index 28: 16.4145, -3.6708.
Missing field/result... skipping.
Retrieving Results for Index 29: -35.1167, 147.3667.
Closest hotel to -35.1167, 147.3667: Best Central House.
Retrieving Results for Index 30: 19.75, 10.25.
Missing field/result... skipping.
Retrieving Results for Index 31: 14.5333, 20.9167.
Closest hotel to 14.5333, 20.9167: Hôtel Trois Étoiles de Biltine.
Retrieving Results for Index 32: 10.8333, -12.5833.
Missing field/result... skipping.
Retrieving Results for Index 33: -17.3411, -39.2208.
Closest hotel to -17.3411, -39.2208: Pousada Carmélia.
Retrieving Results for Index 34: -3.2997, -60.6206.
Closest hotel to -3.2997, -60.6206: TBS HOTEL.
Retrieving Results for Index 35: 18.6853, 12.9164.
Closest hotel to 18.6853, 12.9164: Expeditions Ténére voyages.
Retrieving Results for Index 36: 6.7989, 81.4808.
Closest hotel to 6.7989, 81.4808: Kebiliththa.jetsafari Monaragala.
Retrieving Results for Index 37: -20.1833, 25.2333.
Closest hotel to -20.1833, 25.2333: Gweta Lodge.
Retrieving Results for Index 38: 13.3087, 7.156000000000001.
Closest hotel to 13.3087, 7.156000000000001: Madarounfa centre ville.

In [95]:
hotel_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,Pitimbu,-7.4706,-34.8086,77.00,88,0,4.61,BR,1617600773,Solar da Família Andrade - Pitimbu
1,Busselton,-33.6500,115.3333,84.00,51,2,3.00,AU,1617600779,Pearls Place
2,Grand Gaube,-20.0064,57.6608,84.99,70,5,7.00,MU,1617600808,Talipot Lodge
3,Xai-Xai,-25.0519,33.6442,74.50,67,0,2.26,MZ,1617600811,Complexo da Familia
4,Alice Springs,-23.7000,133.8833,89.01,28,0,9.22,AU,1617600815,Aurora Alice Springs

In [96]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [102]:
# Add marker layer ontop of heat map
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=3,
    info_box_content=hotel_info
)
markers = gmaps.marker_layer(locations)
# Display figure
fig.add_layer(hotel_layer)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))